**Checking TensorFlow Version and GPU Availability**

In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)
print("Is GPU available:", tf.config.list_physical_devices('GPU'))

TensorFlow version: 2.18.0
Is GPU available: []


In [2]:
tf.test.gpu_device_name()

''

**creating tensors**

In [4]:
import numpy as np
a= np.array([1,2,3], dtype=np.int32)

In [5]:
b=[4,5,6]

In [6]:
t_a=tf.convert_to_tensor(a)
t_b=tf.convert_to_tensor(b)

In [8]:
print(t_a)
print(t_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [9]:
t_ones=tf.ones((2,3))
t_ones.shape

TensorShape([2, 3])

In [10]:
t_ones

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [12]:
t_ones.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [13]:
t_ones.dtype

tf.float32

In [14]:
const_tensor= tf.constant([1.2, 5, np.pi])

In [16]:
print(const_tensor)

tf.Tensor([1.2       5.        3.1415927], shape=(3,), dtype=float32)
