In [1]:
import numpy as np

# Generating array

In [2]:
np.array([1,1.5,2])

array([1. , 1.5, 2. ])

In [3]:
# Generate an array of 5 numbers evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [5]:
#Generate an array of values from 0 to 1 with a step of 0.25
np.arange(0,1,0.25)

array([0.  , 0.25, 0.5 , 0.75])

In [6]:
#Create array of shape (3,4)
np.zeros((3,4))# all elements are 0
np.ones((3,4))# all elements are 1
np.full((3,4),2)# all elements are 2

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [7]:
#3*3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## make random arrays

In [8]:
#generates a 2-dimensional NumPy array of shape 3×4 with random floating-point numbers drawn from a uniform distribution over [0,1)
np.random.random((3,4))

array([[0.04341792, 0.87705392, 0.9731919 , 0.52707738],
       [0.12185121, 0.5587983 , 0.65478744, 0.98547099],
       [0.72578091, 0.77156466, 0.89658783, 0.44325858]])

In [9]:
#generates a 2-dimensional numpy array of shape 3*4 filled with random integers drawn from a uniform distribution over the range [0,10)
np.random.randint(10,size=(3,4))

array([[5, 9, 5, 0],
       [7, 1, 1, 8],
       [8, 9, 4, 1]])

In [10]:
#array of shape 3*4 with random floating-point numbers drawn from the standard normal distribution with mean of 0 and a standard deviation of 1
np.random.randn(3,4)

array([[ 0.71345585, -0.32953428, -0.1951781 , -0.54329634],
       [ 0.05834573,  0.55924864, -0.24102171, -0.72100016],
       [-0.53781509, -0.87246574,  1.39742137,  1.07052728]])

In [11]:
#array of shape 3×4 without initializing the entries.
np.empty((3,4))

array([[0.71345585, 0.32953428, 0.1951781 , 0.54329634],
       [0.05834573, 0.55924864, 0.24102171, 0.72100016],
       [0.53781509, 0.87246574, 1.39742137, 1.07052728]])

In [13]:
a=np.array([1,2])
b=np.array([3,4,5])
np.meshgrid(a,b)
#output:[X,Y]
#X: Each row is a copy of a (the first input array).
#Y: Each column is a copy of b (the second input array).

[array([[1, 2],
        [1, 2],
        [1, 2]]),
 array([[3, 3],
        [4, 4],
        [5, 5]])]

# Inspecting array

In [14]:
A=np.random.randn(3,4)
shape=A.shape
size=A.size
len=len(A)
dimentions=A.ndim
dtype=a.dtype

print(f'shape: {shape}')
print(f'size: {size}')
print(f'len: {len}')
print(f'dimentions: {dimentions}')
print(f'dtype: {dtype}')

shape: (3, 4)
size: 12
len: 3
dimentions: 2
dtype: int64


In [19]:
#Copy of the array, cast to a specified type.
x = np.array([1, 2, 2.5])
x.astype(int)

array([1, 2, 2])

# Vector dot-product/Matrix multiplication

In [22]:
# Define two 2-D arrays
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

#all three cells below are idintical

In [23]:
A @ B #matrix multiplication

array([[19, 22],
       [43, 50]])

In [24]:
np.matmul(A,B) #matrix multiplication

array([[19, 22],
       [43, 50]])

In [25]:
np.dot(A,B) #matrix multiplication

array([[19, 22],
       [43, 50]])

# Element-Wise operations

In [26]:
A+B
# np.add(A,B)

array([[ 6,  8],
       [10, 12]])

In [27]:
A-B
# np.subtract(A,B)

array([[-4, -4],
       [-4, -4]])

In [28]:
A*B
# np.multiply(A,B)

array([[ 5, 12],
       [21, 32]])

In [29]:
A/B
# np.divide(A,B)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [30]:
A//B
# np.floor_divide(A,B)

array([[0, 0],
       [0, 0]])

In [31]:
A%B
# np.mod(A,B)

array([[1, 2],
       [3, 4]])

In [32]:
A**B
# np.power(A,B)

array([[    1,    64],
       [ 2187, 65536]])

In [33]:
A==B
# np.equal(A,B)

array([[False, False],
       [False, False]])

In [34]:
A!=B
# np.not_equal(A,B)

array([[ True,  True],
       [ True,  True]])

In [35]:
A>B
# np.greater(A,B)

array([[False, False],
       [False, False]])

In [36]:
A>=B
# np.greater_equal(A,B)

array([[False, False],
       [False, False]])

In [37]:
A<B
# np.less(A,B)

array([[ True,  True],
       [ True,  True]])

In [39]:
A<=B
# np.less_equal(A,B)

array([[ True,  True],
       [ True,  True]])

In [40]:
#returns a boolean array of the same shape as A, where each element is True if the corresponding element in A is NaN, and False otherwise.
np.isnan(A)

array([[False, False],
       [False, False]])

In [44]:
#ceiling, floor, and roundig to 2 d.p
# np.ceil(A)
# np.floor(A)
# np.round(A,2)

array([[1, 2],
       [3, 4]])

In [47]:
#clip to between lower and upper bound
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.clip(a, 1, 8)

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 8])

# Aggregate operations

In [49]:
#All can take argument 'axis=0' to aggregate along an axis. Otherwise aggregate on flattened array
A.mean()

2.5

In [50]:
A.std()

1.118033988749895

In [51]:
np.median(A)

2.5

In [52]:
A.mean(axis=0)
# A.std(axis=0)
# A.sum(axis=0)

array([2., 3.])

In [55]:
#correlation matrix of two vector, or rows of matrix

# Generate a random number generator with a fixed seed for reproducibility
rng = np.random.default_rng(seed=42)
xarr = rng.random((3, 3))

# Calculate the correlation matrix of the rows of xarr
R1 = np.corrcoef(xarr)

In [56]:
u=np.array([1,2,3])
v=np.array([4,5,6])
np.corrcoef(u,v)

array([[1., 1.],
       [1., 1.]])

In [57]:
#Test whether any array element along a given axis evaluates to True
np.any([[True, False], [False, False]], axis=0)

array([ True, False])